{"name": "Verify user can login with valid credentials", "status": "broken", "statusDetails": {"message": "Exception: Allow Notifications button not found after all fallback methods", "trace": "self = <test_login_pytest.TestLogin object at 0x000002A4BE8D1A00>, driver = <appium.webdriver.webdriver.WebDriver (session=\"a3c960f5-aa1b-4a63-a038-9dc8a271365f\")>\n\n    @allure.story(\"Successful Login\")\n    @allure.title(\"Verify user can login with valid credentials\")\n    def test_login_success(self, driver):\n        time.sleep(10)  # Wait for app to load\n        with allure.step(\"1. next button on language selection screen\"):\n            next_button_language_login, used_ocr = smart_find_element(\n            driver,\n            name=\"next_button_language_login\",\n            xpath=\"//android.widget.Button[@text='Next']\",\n            fallback_text=\"Language\"\n            )\n            if next_button_language_login is not None:\n               next_button_language_login.click()\n            elif used_ocr:\n            # If OCR was used, smart_find_element should have already clicked it\n              pass\n            else:\n              raise Exception(\"Next button in language selection not found after all fallback methods\")\n    \n        with allure.step(\"1. Allow notifications\"):\n            allow_notifications_button, used_ocr = smart_find_element(\n                driver,\n                name=\"allow_notifications_button\",\n                xpath=\"//android.widget.Button[@text='Allow']\",\n                fallback_text=\"While using\"\n            )\n            if allow_notifications_button is not None:\n                allow_notifications_button.click()\n            elif not used_ocr:\n>               raise Exception(\"Allow Notifications button not found after all fallback methods\")\nE               Exception: Allow Notifications button not found after all fallback methods\n\ntests\\test_login_pytest.py:43: Exception"}, "steps": [{"name": "1. next button on language selection screen", "status": "passed", "start": 1752062838034, "stop": 1752062850223}, {"name": "1. Allow notifications", "status": "broken", "statusDetails": {"message": "Exception: Allow Notifications button not found after all fallback methods\n", "trace": "  File \"F:\\K_R_F\\tests\\test_login_pytest.py\", line 43, in test_login_success\n    raise Exception(\"Allow Notifications button not found after all fallback methods\")\n"}, "start": 1752062850223, "stop": 1752062862059}], "attachments": [{"name": "Failure Screenshot", "source": "3c6f4991-3ecd-4c96-9060-c6c1510b46a8-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "e58e7ea9-0075-4acc-8124-5b2f63710fdd-attachment.txt", "type": "text/plain"}], "start": 1752062828032, "stop": 1752062862059, "uuid": "960fc193-d1f6-40b6-a59c-57cbc3e99b7c", "historyId": "8cf02fdc5d10e2ec6098ca341efbc915", "testCaseId": "8cf02fdc5d10e2ec6098ca341efbc915", "fullName": "tests.test_login_pytest.TestLogin#test_login_success", "labels": [{"name": "epic", "value": "Login Flow"}, {"name": "story", "value": "Successful Login"}, {"name": "feature", "value": "Authentication"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DELL"}, {"name": "thread", "value": "29528-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_pytest"}]}