{"uid":"c915bba15953fb24","name":"Test valid login","fullName":"tests.test_login#test_login_success","historyId":"86600b41e86dab7ca99f472fa61e4b05","time":{"start":1751969322216,"stop":1751969322216,"duration":0},"status":"broken","statusMessage":"NameError: name 'APK_PATH' is not defined","statusTrace":"@pytest.fixture(scope=\"session\")\n    def driver():\n        # Configure capabilities\n        options = UiAutomator2Options()\n    \n        # Required capabilities\n        options.platform_name = \"Android\"\n        options.automation_name = \"uiautomator2\"  # Explicitly set automation engine\n    \n        # Device capabilities - adjust these to match your device\n        options.device_name = \"emulator-5554\"  # Use actual device name from 'adb devices'\n        options.udid = os.getenv(\"ANDROID_DEVICE_UDID\", None)  # Optional but recommended\n    \n        # App capabilities\n>       options.app = APK_PATH  # Make sure this path is correct\n                      ^^^^^^^^\nE       NameError: name 'APK_PATH' is not defined\n\nconftest.py:23: NameError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"driver","time":{"start":1751969322216,"stop":1751969322216,"duration":0},"status":"broken","statusMessage":"NameError: name 'APK_PATH' is not defined\n","statusTrace":"  File \"C:\\Users\\Pramo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Pramo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Pramo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Pramo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Pramo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"F:\\K_R_F\\conftest.py\", line 23, in driver\n    options.app = APK_PATH  # Make sure this path is correct\n                  ^^^^^^^^\n","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true,"attachmentStep":false,"stepsCount":0}],"afterStages":[],"labels":[{"name":"epic","value":"Login Flow"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_login"},{"name":"host","value":"DELL"},{"name":"thread","value":"21792-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"c915bba15953fb24.json","parameterValues":[]}